### ISSUE TITLE
Dropdown remains after log out

### ISSUE THREAD

**Issue by ThomasVermes** [tertek/redcap-pdf-injector#1]
If logged out from a record home page, the dropdown button remains in the log in page.

![image](https://user-images.githubusercontent.com/75424115/117622102-90e13b00-b172-11eb-90cb-f40c540c5e0c.png)

**Comment by tertek** [comment]
Fixed in 6689fac71626ae87d59ffd50663ec2c6f8dea5c4.
Thanks!
