### ISSUE TITLE
Longitudinal data

### ISSUE THREAD

**Issue by brc0520** [tertek/redcap-pdf-injector#3]
Hi Tertek,

Thank you for this module. They are very helpful. Was wondering if this module accepts longitudinal data? I plan to map the fields to multiple events. Example [event_1][name] on document 1 and [event_2][name] on document 2. Doesn't seem like I'm able to do that. Let me know if you have a way to do that.

Cheers,

Brian

**Comment by tertek** [comment]
Hi Brian,
May I ask you to use the [ REDCap Community Forum](https://community.projectredcap.org/) to post this kind of question.
I will respond you there, since here at Github is more for developer related issues. You can tag your question with #pdfi too, so I get notified.
Thank you :)

**Comment by brc0520** [comment]
Sorry if it's inappropriate here as I don’t have access to the community forum. All good.

Thank you.

Best regards,

Brian CHOW MIEAust CPEng NER
PhD Candidate, NeuRA
M: +61490457878
E: ***@***.*** / ***@***.***
Linkedin: https://www.linkedin.com/in/brianchowvoonyang/

“Grit is living life like it’s a marathon, not a sprint.”- Angela Duckworth

**Comment by tertek** [comment]
Oh sorry I did not know. 

In that case I can help you out here:
I think you can achieve that by creating two different Injections for each event on the same document format.

Then you can bind the PDF field for the first Injection with a variable `event_1_name` using @CALCTEXT([event_1][name] ) and in the other Injection with `event_2_name` using @CALCTEXT([event_2][name] ).

**Comment by brc0520** [comment]
Thanks Tertek.

That might work. I’ll give it a try. Cheers.

Best regards,

Brian CHOW MIEAust CPEng NER
PhD Candidate, NeuRA
M: +61490457878
E: ***@***.*** / ***@***.***
Linkedin: https://www.linkedin.com/in/brianchowvoonyang/

“Grit is living life like it’s a marathon, not a sprint.”- Angela Duckworth
