### ISSUE TITLE
[Feature request] Add QuickFill Button to Step 2 in Injection Edit Modal

### ISSUE THREAD

**Issue by ThomasVermes** [tertek/redcap-pdf-injector#9]
![image](https://user-images.githubusercontent.com/75424115/132304351-5dddb201-ff6c-41a8-8721-ddb579ea1d4c.png)

Would be nice that after importing the pdf, the "redcap filed" will automatically fulfilled with the "pdf field". It can still be adjusted in case of corrections.

**Comment by tertek** [comment]
This is an anti-pattern, since not every user is going to name the form fields the same way as the variables. Defining the placeholder in this way could suggest that variables should be defined equal to form field names. This is not best practise and can be confusing for new users.

**Comment by ThomasVermes** [comment]
Opposite, I really think the best practice would be to rename both of the 
fields in the same way to avoid confusion an to facilitate the mapping. 




From:   "tertek" ***@***.***>
To:     "tertek/redcap-pdf-injector" 
***@***.***>
Cc:     "ThomasVermes" ***@***.***>, "Author" 
***@***.***>
Date:   07.09.2021 09:44
Subject:        Re: [tertek/redcap-pdf-injector] [Feature request] 
Automatic recognizion of field name (#9)



This is an anti-pattern, since not every user is going to name the form 
fields the same way as the variables. Defining the placeholder in this way 
could suggest that variables should be defined equal to form field names. 
This is not best practise and can be confusing for new users.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 



--------------------------------------------------------------------------
This email and any files transmitted with it are confidential and intended 
solely for the use of the individual or entity to whom they are addressed. 
If you have received this email in error, please notify us immediately by 
reply e-mail and delete this message from your system.
--------------------------------------------------------------------------

**Comment by tertek** [comment]
Additionally, variable validation is asynchronously. Setting a default placeholder would break the whole validation procedure/experience.

**Comment by ThomasVermes** [comment]
Set a button which can copy automatically all the field name after the 
import and procedure/experience?
 




From:   "tertek" ***@***.***>
To:     "tertek/redcap-pdf-injector" 
***@***.***>
Cc:     "ThomasVermes" ***@***.***>, "Author" 
***@***.***>
Date:   07.09.2021 09:50
Subject:        Re: [tertek/redcap-pdf-injector] [Feature request] Set 
variable placeholder to form field slug  (#9)



Additionally, variable validation is asynchronously. Setting a default 
placeholder would break the whole validation procedure/experience.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 



--------------------------------------------------------------------------
This email and any files transmitted with it are confidential and intended 
solely for the use of the individual or entity to whom they are addressed. 
If you have received this email in error, please notify us immediately by 
reply e-mail and delete this message from your system.
--------------------------------------------------------------------------

**Comment by tertek** [comment]
Same problem with validation. Too many edge cases. Not worth the effort. Why not just copy & paste?

**Comment by ThomasVermes** [comment]
We could have docs with 50, 100 variables and the doc might also be 
corrected or changed often. That results in a really time consuming task.




From:   "tertek" ***@***.***>
To:     "tertek/redcap-pdf-injector" 
***@***.***>
Cc:     "ThomasVermes" ***@***.***>, "Author" 
***@***.***>
Date:   07.09.2021 10:26
Subject:        Re: [tertek/redcap-pdf-injector] [Feature request] Set 
variable placeholder to form field slug  (#9)



Same problem with validation. Too many edge cases. Not worth the effort. 
Why not just copy & paste?
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 



--------------------------------------------------------------------------
This email and any files transmitted with it are confidential and intended 
solely for the use of the individual or entity to whom they are addressed. 
If you have received this email in error, please notify us immediately by 
reply e-mail and delete this message from your system.
--------------------------------------------------------------------------

**Comment by tertek** [comment]
Added in https://github.com/tertek/redcap-pdf-injector/releases/tag/v1.3.4
